### ISSUE TITLE
Returns error that property is readonly with consecutive `immuta()`

### ISSUE THREAD

**Issue by IniZio** [odo-network/immuta#2]
I tried moving from immer to immuta for the support of Map and Set. However I met an error that stopped me from doing it.

For instance:
```js
this.state = immuta(this.state, draft => {
	draft.todos.push(todo);
	draft.curr = ''
})
```
works but:
```js
this.state = immuta(this.state, draft => {
	draft.todos.push(todo);
})
this.state = immuta(this.state, draft => {
	draft.curr = ''
})
```
will throw error.

It seems like the proxy did not get revoked after the first update? :thinking:

**Comment by bradennapier** [comment]
Ah, no I just need to push an update for that fix.  Will do that soon, sorry.

**Comment by bradennapier** [comment]
Ahh, sorry for the delay. So it appears it just wasnt published but the repo was right.  Building and publishing as we speak.

```javascript
import immuta from './src';
import printDifference from './src/utils/print-difference';

const state = {
  curr: 'something cool',
  todos: [1, 2, 3],
};

let next = immuta(state, draft => {
  draft.todos.push(4);
});

next = immuta(next, draft => {
  draft.curr = '';
});

printDifference(state, next);
```

![image](https://user-images.githubusercontent.com/15365418/43810658-cdeda3a4-9a6d-11e8-9de0-6bb4ba54e14b.png)

**Comment by bradennapier** [comment]
https://github.com/odo-network/immuta/releases/tag/1.3.0

**Comment by bradennapier** [comment]
@IniZio one other thing to mention - while Map should work, I would not use Sets with this. You will have issues and Set likely won't be possible without a completely new implementation of `Set` using Array anyway.

I have provided a fairly in-depth review here: https://github.com/odo-network/immuta/issues/1

`Set` should work `alright` but you will have issues if you end up trying to do anything like `mergeWithDraft` does.  Only way to handle deeper objects within a set is to iterate the entire Set.

We do have tests available for map-set though so overall it should operate as you'd expect within those confines.  Let me know if you run into any issues!  

## [map & set tests](https://github.com/odo-network/immuta/blob/master/tests/map-set.js)

**Comment by IniZio** [comment]
Thanks for the warm advice, I am using it for simple state management so not likely to use Map or Set. :)
